"""renaming columns

Revision ID: 41c585f6b369
Revises: 9a6b0827556b
Create Date: 2026-02-10 22:18:19.650403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41c585f6b369'
down_revision: Union[str, Sequence[str], None] = '9a6b0827556b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_role'), table_name='Users')
    op.drop_table('Users')
    op.drop_table('Products')
    op.add_column('CoxwainEvaluation', sa.Column('evaluation_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_CoxwainEvaluation_cox_id'), 'CoxwainEvaluation', ['cox_id'], unique=False)
    op.create_index(op.f('ix_CoxwainEvaluation_year'), 'CoxwainEvaluation', ['year'], unique=False)
    op.add_column('MemberEnrollmentHistory', sa.Column('member_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('MemberEnrollmentHistory_uid_fkey'), 'MemberEnrollmentHistory', type_='foreignkey')
    op.create_foreign_key(None, 'MemberEnrollmentHistory', 'User', ['member_id'], ['uid'])
    op.drop_column('MemberEnrollmentHistory', 'uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MemberEnrollmentHistory', sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'MemberEnrollmentHistory', type_='foreignkey')
    op.create_foreign_key(op.f('MemberEnrollmentHistory_uid_fkey'), 'MemberEnrollmentHistory', 'User', ['uid'], ['uid'])
    op.drop_column('MemberEnrollmentHistory', 'member_id')
    op.drop_index(op.f('ix_CoxwainEvaluation_year'), table_name='CoxwainEvaluation')
    op.drop_index(op.f('ix_CoxwainEvaluation_cox_id'), table_name='CoxwainEvaluation')
    op.drop_column('CoxwainEvaluation', 'evaluation_id')
    op.create_table('Products',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('revision_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_introduced', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('time_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('Products_pkey'))
    )
    op.create_table('Users',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('passwd_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_created', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('time_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('Users_pkey')),
    sa.UniqueConstraint('email', name=op.f('Users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('Users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_Users_role'), 'Users', ['role'], unique=False)
    # ### end Alembic commands ###