"""init tables and enums

Revision ID: e1906a9d84f7
Revises: 
Create Date: 2026-02-25 00:00:06.225748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1906a9d84f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BoatInfo',
    sa.Column('name', sa.Enum('BUMBLEBEE', 'GRIZZLE', 'WHEELER', 'JUDGE', 'VHP', 'PHATB', 'DZ', 'CLASS', 'MJOLNIR', 'SPACEU', name='boat_name_enum'), nullable=False),
    sa.Column('weight_class', sa.Float(), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('BoatIssues',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('BUMBLEBEE', 'GRIZZLE', 'WHEELER', 'JUDGE', 'VHP', 'PHATB', 'DZ', 'CLASS', 'MJOLNIR', 'SPACEU', name='boat_name_enum'), nullable=True),
    sa.Column('remains_problematic', sa.Boolean(), nullable=False),
    sa.Column('issue_description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_index(op.f('ix_BoatIssues_name'), 'BoatIssues', ['name'], unique=False)
    op.create_index(op.f('ix_BoatIssues_remains_problematic'), 'BoatIssues', ['remains_problematic'], unique=False)
    op.create_table('ExamModel',
    sa.Column('exam_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exam_type', sa.Enum('ERG', 'MILERUN', 'WATER', name='workout_type_enum'), nullable=True),
    sa.Column('measure_type', sa.Enum('DISTANCE', 'TIME', 'WATTAGE', name='workout_measurement_type_enum_enum'), nullable=True),
    sa.PrimaryKeyConstraint('exam_name')
    )
    op.create_table('Product',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_description', sa.TEXT(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('date_introduced', sa.DATE(), nullable=True),
    sa.Column('time_modified', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('RolePermissions',
    sa.Column('role', sa.Enum('ADMIN', 'COACH', 'OFFICER', 'MEMBER', 'INACTIVE', 'ALUMNI', 'WAIT_APPROVAL', 'UNREGISTERED', name='member_role_enum'), nullable=False),
    sa.Column('access_site', sa.Boolean(), nullable=False),
    sa.Column('create_announcements', sa.Boolean(), nullable=False),
    sa.Column('manage_dates', sa.Boolean(), nullable=False),
    sa.Column('manage_members', sa.Boolean(), nullable=False),
    sa.Column('manage_roles', sa.Boolean(), nullable=False),
    sa.Column('view_funds', sa.Boolean(), nullable=False),
    sa.Column('view_roster', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('Semester',
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Enum('SPRING', 'SUMMER', 'FALL', name='semester_enum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('semester_id')
    )
    op.create_index(op.f('ix_Semester_end_date'), 'Semester', ['end_date'], unique=False)
    op.create_index(op.f('ix_Semester_semester'), 'Semester', ['semester'], unique=False)
    op.create_index(op.f('ix_Semester_start_date'), 'Semester', ['start_date'], unique=False)
    op.create_index(op.f('ix_Semester_year'), 'Semester', ['year'], unique=False)
    op.create_table('User',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('passwd_hash', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'COACH', 'OFFICER', 'MEMBER', 'INACTIVE', 'ALUMNI', 'WAIT_APPROVAL', 'UNREGISTERED', name='member_role_enum'), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('join_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_User_first_name'), 'User', ['first_name'], unique=False)
    op.create_index(op.f('ix_User_join_date'), 'User', ['join_date'], unique=False)
    op.create_index(op.f('ix_User_last_name'), 'User', ['last_name'], unique=False)
    op.create_index(op.f('ix_User_role'), 'User', ['role'], unique=False)
    op.create_table('VolunteeringDate',
    sa.Column('volunteer_date', sa.Date(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_heads_required', sa.Integer(), nullable=False),
    sa.Column('start_time', postgresql.TIME(), nullable=False),
    sa.Column('end_time', postgresql.TIME(), nullable=True),
    sa.PrimaryKeyConstraint('volunteer_date')
    )
    op.create_table('Availability',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('present_monday', sa.Boolean(), nullable=False),
    sa.Column('present_tuesday', sa.Boolean(), nullable=False),
    sa.Column('present_wednesday', sa.Boolean(), nullable=False),
    sa.Column('present_thursday', sa.Boolean(), nullable=False),
    sa.Column('present_friday', sa.Boolean(), nullable=False),
    sa.Column('present_saturday', sa.Boolean(), nullable=False),
    sa.Column('present_sunday', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['User.uid'], ),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_index(op.f('ix_Availability_present_friday'), 'Availability', ['present_friday'], unique=False)
    op.create_index(op.f('ix_Availability_present_monday'), 'Availability', ['present_monday'], unique=False)
    op.create_index(op.f('ix_Availability_present_saturday'), 'Availability', ['present_saturday'], unique=False)
    op.create_index(op.f('ix_Availability_present_sunday'), 'Availability', ['present_sunday'], unique=False)
    op.create_index(op.f('ix_Availability_present_thursday'), 'Availability', ['present_thursday'], unique=False)
    op.create_index(op.f('ix_Availability_present_tuesday'), 'Availability', ['present_tuesday'], unique=False)
    op.create_index(op.f('ix_Availability_present_wednesday'), 'Availability', ['present_wednesday'], unique=False)
    op.create_table('Coxwain',
    sa.Column('cox_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cox_id'], ['User.uid'], ),
    sa.PrimaryKeyConstraint('cox_id')
    )
    op.create_table('Exam',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('exam_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('date_occurred', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['exam_name'], ['ExamModel.exam_name'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['Semester.semester_id'], ),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_index(op.f('ix_Exam_exam_name'), 'Exam', ['exam_name'], unique=False)
    op.create_index(op.f('ix_Exam_semester_id'), 'Exam', ['semester_id'], unique=False)
    op.create_table('MemberEnrollmentHistory',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'COACH', 'OFFICER', 'MEMBER', 'INACTIVE', 'ALUMNI', 'WAIT_APPROVAL', 'UNREGISTERED', name='member_role_enum'), nullable=False),
    sa.Column('dues_paid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['User.uid'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['Semester.semester_id'], ),
    sa.PrimaryKeyConstraint('member_id', 'semester_id')
    )
    op.create_table('RegisteredVolunteers',
    sa.Column('volunteer_date', sa.Date(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('volunteered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['User.uid'], ),
    sa.ForeignKeyConstraint(['volunteer_date'], ['VolunteeringDate.volunteer_date'], ),
    sa.PrimaryKeyConstraint('volunteer_date', 'member_id')
    )
    op.create_table('Rower',
    sa.Column('rower_id', sa.Uuid(), nullable=False),
    sa.Column('times_rowed', sa.Integer(), nullable=False),
    sa.Column('total_pace_contribution', sa.Integer(), nullable=False),
    sa.Column('avg_wattage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rower_id'], ['User.uid'], ),
    sa.PrimaryKeyConstraint('rower_id')
    )
    op.create_table('RowerIssues',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('issue', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['User.uid'], ),
    sa.PrimaryKeyConstraint('issue_id', 'member_id')
    )
    op.create_table('RowerPerformanceRecord',
    sa.Column('exam_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('date_occurred', sa.Date(), nullable=False),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('value_time', sa.Interval(), nullable=True),
    sa.ForeignKeyConstraint(['exam_name'], ['ExamModel.exam_name'], ),
    sa.ForeignKeyConstraint(['member_id'], ['User.uid'], ),
    sa.PrimaryKeyConstraint('exam_name', 'member_id')
    )
    op.create_table('ScheduledAbsence',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('absence_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['User.uid'], ),
    sa.PrimaryKeyConstraint('member_id', 'absence_date')
    )
    op.create_table('SemesterAbsence',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('date_occurred', sa.Date(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['User.uid'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['Semester.semester_id'], ),
    sa.PrimaryKeyConstraint('member_id', 'date_occurred')
    )
    op.create_index(op.f('ix_SemesterAbsence_semester_id'), 'SemesterAbsence', ['semester_id'], unique=False)
    op.create_table('Workout',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('date_occurred', sa.Date(), nullable=False),
    sa.Column('workout_name', sa.VARCHAR(), nullable=False),
    sa.Column('workout_type', sa.Enum('ERG', 'MILERUN', 'WATER', name='workout_type_enum'), nullable=False),
    sa.Column('sequence_num', sa.Integer(), nullable=False),
    sa.Column('desc', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['Semester.semester_id'], ),
    sa.PrimaryKeyConstraint('workout_id')
    )
    op.create_index(op.f('ix_Workout_date_occurred'), 'Workout', ['date_occurred'], unique=False)
    op.create_index(op.f('ix_Workout_semester_id'), 'Workout', ['semester_id'], unique=False)
    op.create_index(op.f('ix_Workout_sequence_num'), 'Workout', ['sequence_num'], unique=False)
    op.create_index(op.f('ix_Workout_workout_name'), 'Workout', ['workout_name'], unique=False)
    op.create_index(op.f('ix_Workout_workout_type'), 'Workout', ['workout_type'], unique=False)
    op.create_table('BoatRoutineIdentifier',
    sa.Column('boat_routine_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('boat', sa.Enum('BUMBLEBEE', 'GRIZZLE', 'WHEELER', 'JUDGE', 'VHP', 'PHATB', 'DZ', 'CLASS', 'MJOLNIR', 'SPACEU', name='boat_name_enum'), nullable=True),
    sa.Column('coxwain_id', sa.Uuid(), nullable=False),
    sa.Column('lineup_type', sa.Enum('MEN', 'WOMEN', 'MIXED', name='boat_lineup_type_enum'), nullable=True),
    sa.Column('anticipated_pace', sa.Interval(), nullable=False),
    sa.ForeignKeyConstraint(['coxwain_id'], ['Coxwain.cox_id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['Workout.workout_id'], ),
    sa.PrimaryKeyConstraint('boat_routine_id')
    )
    op.create_index(op.f('ix_BoatRoutineIdentifier_boat'), 'BoatRoutineIdentifier', ['boat'], unique=False)
    op.create_index(op.f('ix_BoatRoutineIdentifier_coxwain_id'), 'BoatRoutineIdentifier', ['coxwain_id'], unique=False)
    op.create_index(op.f('ix_BoatRoutineIdentifier_lineup_type'), 'BoatRoutineIdentifier', ['lineup_type'], unique=False)
    op.create_index(op.f('ix_BoatRoutineIdentifier_workout_id'), 'BoatRoutineIdentifier', ['workout_id'], unique=False)
    op.create_table('BoatWorkoutRoutine',
    sa.Column('boat_routine_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('sequence_num', sa.Integer(), nullable=False),
    sa.Column('boat', sa.Enum('BUMBLEBEE', 'GRIZZLE', 'WHEELER', 'JUDGE', 'VHP', 'PHATB', 'DZ', 'CLASS', 'MJOLNIR', 'SPACEU', name='boat_name_enum'), nullable=False),
    sa.Column('target_measurement_type', sa.Enum('DISTANCE', 'TIME', 'WATTAGE', name='workout_measurement_type_enum_enum'), nullable=False),
    sa.Column('result', sa.Integer(), nullable=False),
    sa.Column('target_rate', sa.Integer(), nullable=True),
    sa.Column('total_time', sa.Interval(), nullable=True),
    sa.Column('min_pace', sa.Interval(), nullable=True),
    sa.Column('max_pace', sa.Interval(), nullable=True),
    sa.Column('avg_pace', sa.Interval(), nullable=True),
    sa.Column('avg_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['Workout.workout_id'], ),
    sa.PrimaryKeyConstraint('boat_routine_id')
    )
    op.create_index(op.f('ix_BoatWorkoutRoutine_boat'), 'BoatWorkoutRoutine', ['boat'], unique=False)
    op.create_index(op.f('ix_BoatWorkoutRoutine_sequence_num'), 'BoatWorkoutRoutine', ['sequence_num'], unique=False)
    op.create_index(op.f('ix_BoatWorkoutRoutine_target_measurement_type'), 'BoatWorkoutRoutine', ['target_measurement_type'], unique=False)
    op.create_index(op.f('ix_BoatWorkoutRoutine_target_rate'), 'BoatWorkoutRoutine', ['target_rate'], unique=False)
    op.create_index(op.f('ix_BoatWorkoutRoutine_workout_id'), 'BoatWorkoutRoutine', ['workout_id'], unique=False)
    op.create_table('CoxwainEvaluation',
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('cox_id', sa.Uuid(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DATE(), nullable=True),
    sa.Column('feedback', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['cox_id'], ['Coxwain.cox_id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['Semester.semester_id'], ),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_index(op.f('ix_CoxwainEvaluation_cox_id'), 'CoxwainEvaluation', ['cox_id'], unique=False)
    op.create_index(op.f('ix_CoxwainEvaluation_date_created'), 'CoxwainEvaluation', ['date_created'], unique=False)
    op.create_index(op.f('ix_CoxwainEvaluation_semester_id'), 'CoxwainEvaluation', ['semester_id'], unique=False)
    op.create_table('LandWorkoutRoutine',
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('sequence_num', sa.Integer(), nullable=False),
    sa.Column('target_measurement_type', sa.Enum('DISTANCE', 'TIME', 'WATTAGE', name='workout_measurement_type_enum'), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('target_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['Workout.workout_id'], ),
    sa.PrimaryKeyConstraint('routine_id')
    )
    op.create_index(op.f('ix_LandWorkoutRoutine_sequence_num'), 'LandWorkoutRoutine', ['sequence_num'], unique=False)
    op.create_index(op.f('ix_LandWorkoutRoutine_target_measurement_type'), 'LandWorkoutRoutine', ['target_measurement_type'], unique=False)
    op.create_index(op.f('ix_LandWorkoutRoutine_target_rate'), 'LandWorkoutRoutine', ['target_rate'], unique=False)
    op.create_index(op.f('ix_LandWorkoutRoutine_target_value'), 'LandWorkoutRoutine', ['target_value'], unique=False)
    op.create_index(op.f('ix_LandWorkoutRoutine_workout_id'), 'LandWorkoutRoutine', ['workout_id'], unique=False)
    op.create_table('MemberExamPerformance',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('completion_time', sa.Interval(), nullable=False),
    sa.Column('avg_pace', sa.Interval(), nullable=True),
    sa.Column('avg_rate', sa.Integer(), nullable=True),
    sa.Column('avg_wattage', sa.Integer(), nullable=True),
    sa.Column('peak_wattage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['Exam.exam_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['User.uid'], ),
    sa.PrimaryKeyConstraint('exam_id', 'member_id')
    )
    op.create_index(op.f('ix_MemberExamPerformance_completion_time'), 'MemberExamPerformance', ['completion_time'], unique=False)
    op.create_table('BoatFeedback',
    sa.Column('boat_routine_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('evaluation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['boat_routine_id'], ['BoatWorkoutRoutine.boat_routine_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['User.uid'], ),
    sa.PrimaryKeyConstraint('boat_routine_id', 'member_id')
    )
    op.create_table('MemberWorkoutPerformance',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('workout_performed_id', sa.Integer(), nullable=False),
    sa.Column('total_time', sa.Interval(), nullable=True),
    sa.Column('avg_pace', sa.Interval(), nullable=True),
    sa.Column('avg_rate', sa.Integer(), nullable=True),
    sa.Column('avg_wattage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['User.uid'], ),
    sa.ForeignKeyConstraint(['workout_performed_id'], ['LandWorkoutRoutine.routine_id'], ),
    sa.PrimaryKeyConstraint('member_id', 'workout_performed_id')
    )
    op.create_index(op.f('ix_MemberWorkoutPerformance_avg_pace'), 'MemberWorkoutPerformance', ['avg_pace'], unique=False)
    op.create_table('RowerOnBoat',
    sa.Column('boat_routine_id', sa.Integer(), nullable=False),
    sa.Column('rower_id', sa.Uuid(), nullable=False),
    sa.Column('seat_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boat_routine_id'], ['BoatRoutineIdentifier.boat_routine_id'], ),
    sa.ForeignKeyConstraint(['rower_id'], ['Rower.rower_id'], ),
    sa.PrimaryKeyConstraint('boat_routine_id', 'rower_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RowerOnBoat')
    op.drop_index(op.f('ix_MemberWorkoutPerformance_avg_pace'), table_name='MemberWorkoutPerformance')
    op.drop_table('MemberWorkoutPerformance')
    op.drop_table('BoatFeedback')
    op.drop_index(op.f('ix_MemberExamPerformance_completion_time'), table_name='MemberExamPerformance')
    op.drop_table('MemberExamPerformance')
    op.drop_index(op.f('ix_LandWorkoutRoutine_workout_id'), table_name='LandWorkoutRoutine')
    op.drop_index(op.f('ix_LandWorkoutRoutine_target_value'), table_name='LandWorkoutRoutine')
    op.drop_index(op.f('ix_LandWorkoutRoutine_target_rate'), table_name='LandWorkoutRoutine')
    op.drop_index(op.f('ix_LandWorkoutRoutine_target_measurement_type'), table_name='LandWorkoutRoutine')
    op.drop_index(op.f('ix_LandWorkoutRoutine_sequence_num'), table_name='LandWorkoutRoutine')
    op.drop_table('LandWorkoutRoutine')
    op.drop_index(op.f('ix_CoxwainEvaluation_semester_id'), table_name='CoxwainEvaluation')
    op.drop_index(op.f('ix_CoxwainEvaluation_date_created'), table_name='CoxwainEvaluation')
    op.drop_index(op.f('ix_CoxwainEvaluation_cox_id'), table_name='CoxwainEvaluation')
    op.drop_table('CoxwainEvaluation')
    op.drop_index(op.f('ix_BoatWorkoutRoutine_workout_id'), table_name='BoatWorkoutRoutine')
    op.drop_index(op.f('ix_BoatWorkoutRoutine_target_rate'), table_name='BoatWorkoutRoutine')
    op.drop_index(op.f('ix_BoatWorkoutRoutine_target_measurement_type'), table_name='BoatWorkoutRoutine')
    op.drop_index(op.f('ix_BoatWorkoutRoutine_sequence_num'), table_name='BoatWorkoutRoutine')
    op.drop_index(op.f('ix_BoatWorkoutRoutine_boat'), table_name='BoatWorkoutRoutine')
    op.drop_table('BoatWorkoutRoutine')
    op.drop_index(op.f('ix_BoatRoutineIdentifier_workout_id'), table_name='BoatRoutineIdentifier')
    op.drop_index(op.f('ix_BoatRoutineIdentifier_lineup_type'), table_name='BoatRoutineIdentifier')
    op.drop_index(op.f('ix_BoatRoutineIdentifier_coxwain_id'), table_name='BoatRoutineIdentifier')
    op.drop_index(op.f('ix_BoatRoutineIdentifier_boat'), table_name='BoatRoutineIdentifier')
    op.drop_table('BoatRoutineIdentifier')
    op.drop_index(op.f('ix_Workout_workout_type'), table_name='Workout')
    op.drop_index(op.f('ix_Workout_workout_name'), table_name='Workout')
    op.drop_index(op.f('ix_Workout_sequence_num'), table_name='Workout')
    op.drop_index(op.f('ix_Workout_semester_id'), table_name='Workout')
    op.drop_index(op.f('ix_Workout_date_occurred'), table_name='Workout')
    op.drop_table('Workout')
    op.drop_index(op.f('ix_SemesterAbsence_semester_id'), table_name='SemesterAbsence')
    op.drop_table('SemesterAbsence')
    op.drop_table('ScheduledAbsence')
    op.drop_table('RowerPerformanceRecord')
    op.drop_table('RowerIssues')
    op.drop_table('Rower')
    op.drop_table('RegisteredVolunteers')
    op.drop_table('MemberEnrollmentHistory')
    op.drop_index(op.f('ix_Exam_semester_id'), table_name='Exam')
    op.drop_index(op.f('ix_Exam_exam_name'), table_name='Exam')
    op.drop_table('Exam')
    op.drop_table('Coxwain')
    op.drop_index(op.f('ix_Availability_present_wednesday'), table_name='Availability')
    op.drop_index(op.f('ix_Availability_present_tuesday'), table_name='Availability')
    op.drop_index(op.f('ix_Availability_present_thursday'), table_name='Availability')
    op.drop_index(op.f('ix_Availability_present_sunday'), table_name='Availability')
    op.drop_index(op.f('ix_Availability_present_saturday'), table_name='Availability')
    op.drop_index(op.f('ix_Availability_present_monday'), table_name='Availability')
    op.drop_index(op.f('ix_Availability_present_friday'), table_name='Availability')
    op.drop_table('Availability')
    op.drop_table('VolunteeringDate')
    op.drop_index(op.f('ix_User_role'), table_name='User')
    op.drop_index(op.f('ix_User_last_name'), table_name='User')
    op.drop_index(op.f('ix_User_join_date'), table_name='User')
    op.drop_index(op.f('ix_User_first_name'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Semester_year'), table_name='Semester')
    op.drop_index(op.f('ix_Semester_start_date'), table_name='Semester')
    op.drop_index(op.f('ix_Semester_semester'), table_name='Semester')
    op.drop_index(op.f('ix_Semester_end_date'), table_name='Semester')
    op.drop_table('Semester')
    op.drop_table('RolePermissions')
    op.drop_table('Product')
    op.drop_table('ExamModel')
    op.drop_index(op.f('ix_BoatIssues_remains_problematic'), table_name='BoatIssues')
    op.drop_index(op.f('ix_BoatIssues_name'), table_name='BoatIssues')
    op.drop_table('BoatIssues')
    op.drop_table('BoatInfo')
    # ### end Alembic commands ###